name: whyleloop_sdk
description: Whyleloop Deferred Deep Linking SDK for Flutter
version: 0.1.0
homepage: https://whyleloop.app

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
